### ISSUE TITLE
Can't login on the application

### ISSUE THREAD

**Issue by dukenst2006** [forddyce/mlm-2#1]
Hello @forddyce 
Congratulations for this great work, I installed the app, migrate and seed the databse.  i can't login with the credentials on the seeding file . I checked the database, every things are ok, the user and the password are there. any idea how to fix that. thanks in advance!

Best

**Comment by forddyce** [comment]
@dukenst2006  the one seeded on database is admin, you have to go to admin url first (/admin by default), login with username: admin and password: password, from there you can create a root member used on front page

**Comment by forddyce** [comment]
@dukenst2006 by the way if you are here because of the original readme (with VueJS and sales/inventory part) then you are in wrong place. That readme is from my old project (which is private cannot be shared, sorry). This is for multi level marketing system.
