### ISSUE TITLE
No password for the various users provided

### ISSUE THREAD

**Issue by brytey2k** [forddyce/mlm-2#2]
No password for the various users provided. Could you please provide this

**Comment by forddyce** [comment]
Check the database seeder. Should be `password`.

**Comment by brytey2k** [comment]
That is the right password but I get the error "User is not a member". I have called the UserSeeder. I get the the error with these credentials: username: user..... Password: password

**Comment by forddyce** [comment]
then you haven't read the readme

**Comment by brytey2k** [comment]
I did. I just added the UserSeeder that's all. But I did exactly what was
required in the readme

**Comment by forddyce** [comment]
I don't think you are a good developer if you don't know what you did wrong.

And, pretty sure you didn't read this part: Change
vendor/cartalyst/sentinel/src/Users/EloquentUser.php with EloquentUser.php on
root
